config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create]
  match '/sign-out', to: 'sessions#destroy', via: :get, as: :sign_out

  resources :users, only: [:create, :show] do
    scope module: :users do
      resource :followings, only: [:create, :destroy]
    end # scope module: :users
  end # resources :users

  resource :username_searches, only: [:create]
  resource :profile, only: [:show, :edit, :update]
  resource :followings, only: [:show]
  resource :followers, only: [:show]
  resource :favorites, only: [:show]

  resource :timeline, only: [:show]
  resources :tweets, only: [:create] do
    scope module: :tweets do
      resource :favorite, only: [:create, :destroy]
    end # scope module: :tweets
  end # resources :tweets

  root 'users#new'
end

app/models/tweet.rb
# the tweet model
class Tweet < ApplicationRecord
  belongs_to :author, class_name: User
  has_many :mentions

  attr_accessor :favorited_by_current_user

  validates :content, presence: true
  validates :author_id, presence: true
end # Tweet

app/controllers/tweets/favorites_controller.rb
module Tweets
  class FavoritesController < ApplicationController
    include Authorized
    include FavoriteHelpers

    def create
      Favorite.create( favorite_query_params(tweet) )
      redirect_to request.referer
    end

    def destroy
      Favorite.where( favorite_query_params(tweet) ).delete_all
      redirect_to request.referer
    end

    private

    def tweet
      Tweet.find(params[:tweet_id])
    end
  end
end # module Tweets

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include Authorized

  def create
    flash.delete(:tweet_errors)
    params.require(:tweet)
    tweet = TweetService.create_tweet( params[:tweet].permit!.merge(author: current_user) )
    flash[:tweet_errors] = tweet.errors.full_messages unless tweet.persisted?
    redirect_to timeline_path
  end
end

app/views/tweets/_form.html.haml
- if flash[:tweet_errors]
  .alert.alert-danger.alert-dismissable
    %button.close{ type: 'button', data: { dismiss: 'alert' } }
      x
    %strong
      Oops!
    - flash[:tweet_errors].each do |error_message|
      .error-message
        = error_message

= form_for :tweet, url: tweets_path, html: { class: 'form-horizontal' } do |f|
  %fieldset
    %div
      = f.label :content, 'What do you want to say', class: 'control-label'
    %div
      = f.text_area :content, class: 'form-control'
    %div
      %button.btn.btn-primary.pull-right{ type: 'submit' }
        Submit

app/views/tweets/_timeline.html.haml
- if signed_in?
  %ul.nav.nav-tabs
    %li.active
      - if tweet.favorited_by_current_user
        = link_to 'Unfavorite', tweet_favorite_path( tweet.id ), method: :delete
      - else
        = link_to 'Favorite', tweet_favorite_path( tweet.id ), method: :post
.well
  %blockquote
    %p
      = mention_link_content( tweet )
    %small
      - if signed_in?
        = link_to tweet.author.username, user_path( tweet.author.username )
      - else
        = tweet.author.username