config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create]
  match '/sign-out', to: 'sessions#destroy', via: :get, as: :sign_out

  resources :users, only: [:create, :show] do
    scope module: :users do
      resource :followings, only: [:create, :destroy]
    end # scope module: :users
  end # resources :users

  resource :username_searches, only: [:create]
  resource :profile, only: [:show, :edit, :update]
  resource :followings, only: [:show]
  resource :followers, only: [:show]
  resource :favorites, only: [:show]

  resource :timeline, only: [:show]
  resources :tweets, only: [:create] do
    scope module: :tweets do
      resource :favorite, only: [:create, :destroy]
    end # scope module: :tweets
  end # resources :tweets

  root 'users#new'
end

app/models/user.rb
# the user model
class User < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mappings do
    indexes :username, type: 'keyword'
  end

  has_secure_password
  attr_accessor :following_current_user

  validates :email, presence: true, format: { with: /.*@.*/ }, uniqueness: true
  validates :username, presence: true, format: { with: /\A[A-Za-z][A-Za-z_0-9]*\z/ }, uniqueness: true

  class << self # class methods
    def find_by_email_or_username( email_or_username )
      return nil if email_or_username.nil?

      if email_or_username.include?('@')
        User.find_by(email: email_or_username)
      else
        User.find_by(username: email_or_username)
      end
    end

    def username_search( username )
      where(id: search(
        query: {
          prefix: {
            username: {
              value: username
            }
          }
        }
      ).records.ids)
    end
  end # class methods
end # User

app/controllers/users/followings_controller.rb
module Users
  class FollowingsController < ApplicationController
    include Authorized
    include FollowingHelpers

    def create
      Following.create( following_query_params(followed_user) )
      redirect_to user_path( params[:user_id] )
    end

    def destroy
      following_query( followed_user ).delete_all
      redirect_to user_path( params[:user_id] )
    end

    private

    def followed_user
      User.find_by(username: params[:user_id])
    end
  end
end # module Users

app/controllers/users_controller.rb
# the users controller
class UsersController < ApplicationController
  include Authorized
  include FollowingHelpers

  skip_before_action :require_user, only: [:new, :create]

  def new
    redirect_to timeline_path if signed_in?

    @recent_tweets = Tweet.includes(:mentions).order(id: :desc).limit(10)
  end

  def create
    params.require(:user)

    @user = User.create( params[:user].permit! )
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to timeline_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by( username: params[:id] )
    @following = current_user_following_user?( @user )

    @recent_tweets = Tweet.includes(:mentions).where(author_id: @user.id).order(id: :desc).limit(10)
  end
end

app/views/users/_as_following.html.haml
%ul.nav.nav-tabs
  %li.active
    - if user.following_current_user
      = link_to "Unfollow", user_followings_path( user.username ), method: :delete
    - else
      = link_to "Follow", user_followings_path( user.username ), method: :post
.well
  %h3
    %a{ href: user_path( user.username ) }
      = user.username

app/views/users/_form.html.haml
- if @user.try(:errors) && !@user.errors.empty?
  .alert.alert-danger.alert-dismissable
    %button.close{ type: 'button', data: { dismiss: 'alert' } }
      x
    %strong
      Oops!
    - @user.errors.full_messages.each do |error_message|
      .error-message
        = error_message
= form_for (current_user || :user), url: form_post_path, html: { class: 'form-horizontal' } do |f|
  %fieldset
    .form-group
      = f.text_field :username, placeholder: 'Username', class: 'form-control'
    .form-group
      = f.text_field :email, placeholder: 'Email', class: 'form-control'
    .form-group
      = f.password_field :password, placeholder: 'Password', class: 'form-control'
    .form-group
      = f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'form-control'
    .form-group
      %button.btn.btn-primary{ type: 'submit' }
        Submit

app/views/users/_username_query.html.haml
%a.list-group-item{ href: user_path( user.username ) }
  = user.username

app/views/users/new.html.haml
- content_for :side_bar do
  %h1 Create an Account
  .well
    = render partial: 'form', locals: { form_post_path: users_path }

%h1 What's Happening
= render partial: 'tweets/timeline', collection: @recent_tweets, as: :tweet

app/views/users/show.html.haml
- content_for :side_bar do
  - unless current_user == @user
    %h1
      Actions to take
    .list-group
      - if @following
        = link_to "Unfollow #{@user.username}", user_followings_path( @user.username ), method: :delete, class: 'list-group-item'
      - else
        = link_to "Follow #{@user.username}", user_followings_path( @user.username ), method: :post, class: 'list-group-item'

%h1
  = @user.username

= render partial: 'tweets/timeline', collection: @recent_tweets, as: :tweet